name: Show Datetime

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  display-datetime:
    runs-on: ubuntu-latest
    steps:
      - name: Print current date and time
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "UTC: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "Moscow: $(TZ='Europe/Moscow' date '+%Y-%m-%d +%H:%M:%S')"
