name: Show Datetime

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  display-datetime:
    runs-on: ubuntu-latest
    steps:
      - name: Print current date and time
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Date: $(date +'%Y-%m-%d')"
          echo "Time: $(date +'%H:%M:%S')"
