name: Maven Package and Push

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ feature/** ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Verify JAR creation
        run: |
          echo "Checking created JAR files:"
          ls -la target/
          if [ -f "target/*.jar" ]; then
            echo "JAR file successfully created"
            jar tf target/*.jar | head -10
          else
            echo "JAR file not found"
            exit 1
          fi

      - name: Push to branch (optional)
        if: github.event_name == 'push'
        run: |
          echo "Push event detected, current branch: ${{ github.ref }}"
          # Здесь можно добавить дополнительные действия с push
          # Например, отправку артефактов или деплой

      - name: Success notification
        run: echo "Maven package completed successfully on branch ${{ github.ref }}"